export { default as AdministrationCalendar } from './AdministrationCalendar'
export { default as AdministrationUsers } from './AdministrationUsers'
export { default as AdministrationEmployees } from './AdministrationEmployees'
export { default as AdministrationNews } from './AdministrationNews'
export { default as AdministrationOrders } from './AdministrationOrders'
export { default as AdministrationServices } from './AdministrationServices'
export { default as AdministrationWelcome } from './AdministrationWelcome'
export { default as UserSettings } from './UserSettings'

export * from './components/index'
